import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * The full schema (implementation plan, "Database schema"): Tracked Companies,
 * Articles, Candidates (a Mention is a relevant Candidate), Runs and their
 * per-company errors, Alert Digests and the collector heartbeat.
 *
 * Mirrors the entities in `src/database/entities/`, so `migration:generate`
 * reports no changes, plus two expression indexes TypeORM cannot describe
 * (declared `synchronize: false` on the entities):
 * - `UQ_tracked_companies_display_name_live` — display names are unique,
 *   case-insensitively, among companies that are not deactivated (ADR-010);
 * - `UQ_runs_one_active` — at most one Run is queued or running (ADR-009).
 */
export class CreateSchema1791369144415 implements MigrationInterface {
  readonly name = 'CreateSchema1791369144415';

  async up(queryRunner: QueryRunner): Promise<void> {
    // Runs
    await queryRunner.query(`CREATE TYPE "run_type" AS ENUM ('backfill', 'daily_check')`);
    await queryRunner.query(
      `CREATE TYPE "run_status" AS ENUM ('queued', 'running', 'completed', 'completed_with_errors', 'failed', 'interrupted')`,
    );
    await queryRunner.query(`CREATE TYPE "run_trigger" AS ENUM ('dashboard', 'schedule')`);
    await queryRunner.query(`
      CREATE TABLE "runs" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "type" "run_type" NOT NULL,
        "status" "run_status" NOT NULL DEFAULT 'queued',
        "params" jsonb NOT NULL,
        "trigger" "run_trigger" NOT NULL,
        "progress" jsonb,
        "error" text,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "started_at" TIMESTAMP WITH TIME ZONE,
        "finished_at" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "PK_runs" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(`CREATE INDEX "IDX_runs_created_at" ON "runs" ("created_at")`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_runs_one_active" ON "runs" ((true)) WHERE "status" IN ('queued', 'running')`,
    );

    // Collector heartbeat
    await queryRunner.query(`CREATE TYPE "collector_state" AS ENUM ('idle', 'importing', 'running')`);
    await queryRunner.query(`
      CREATE TABLE "collector_heartbeat" (
        "id" smallint NOT NULL DEFAULT '1',
        "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL,
        "state" "collector_state" NOT NULL,
        "ollama_ok" boolean,
        "ollama_model" text,
        "detail" text,
        CONSTRAINT "CHK_collector_heartbeat_single_row" CHECK ("id" = 1),
        CONSTRAINT "PK_collector_heartbeat" PRIMARY KEY ("id")
      )`);

    // Tracked Companies
    await queryRunner.query(
      `CREATE TYPE "tracked_company_status" AS ENUM ('active', 'needs_review', 'deactivated')`,
    );
    await queryRunner.query(`
      CREATE TABLE "tracked_companies" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "source_name" text,
        "display_name" text NOT NULL,
        "aliases" text array NOT NULL DEFAULT '{}',
        "domain" text,
        "description" text,
        "search_terms" text array NOT NULL DEFAULT '{}',
        "status" "tracked_company_status" NOT NULL,
        "review_reason" text,
        "coverage_capped" boolean NOT NULL DEFAULT false,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_tracked_companies" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(`CREATE INDEX "IDX_tracked_companies_status" ON "tracked_companies" ("status")`);
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_tracked_companies_source_name" ON "tracked_companies" ("source_name") WHERE "source_name" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_tracked_companies_display_name_live" ON "tracked_companies" (lower("display_name")) WHERE "status" <> 'deactivated'`,
    );

    // Per-company Run errors
    await queryRunner.query(`
      CREATE TABLE "run_company_errors" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "run_id" integer NOT NULL,
        "company_id" integer NOT NULL,
        "stage" text NOT NULL,
        "message" text NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_run_company_errors" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(`CREATE INDEX "IDX_run_company_errors_run" ON "run_company_errors" ("run_id")`);

    // Articles
    await queryRunner.query(`
      CREATE TABLE "articles" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "google_article_id" text NOT NULL,
        "title" text NOT NULL,
        "snippet" text NOT NULL,
        "outlet_name" text NOT NULL,
        "outlet_url" text NOT NULL,
        "google_url" text NOT NULL,
        "publisher_url" text,
        "published_at" TIMESTAMP WITH TIME ZONE NOT NULL,
        "language" text NOT NULL,
        "edition" text NOT NULL,
        "first_fetched_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_articles_google_article_id" UNIQUE ("google_article_id"),
        CONSTRAINT "PK_articles" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(`CREATE INDEX "IDX_articles_published_at" ON "articles" ("published_at")`);

    // Candidates (and Mentions)
    await queryRunner.query(`CREATE TYPE "candidate_relevance" AS ENUM ('pending', 'relevant', 'rejected')`);
    await queryRunner.query(`CREATE TYPE "relevance_method" AS ENUM ('llm', 'name_absent')`);
    await queryRunner.query(`CREATE TYPE "sentiment" AS ENUM ('positive', 'negative', 'neutral')`);
    await queryRunner.query(`
      CREATE TABLE "candidates" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "article_id" integer NOT NULL,
        "company_id" integer NOT NULL,
        "fetched_in_run_id" integer NOT NULL,
        "relevance" "candidate_relevance" NOT NULL DEFAULT 'pending',
        "relevance_method" "relevance_method",
        "relevance_reason" text,
        "relevance_classified_at" TIMESTAMP WITH TIME ZONE,
        "sentiment" "sentiment",
        "sentiment_reason" text,
        "sentiment_classified_at" TIMESTAMP WITH TIME ZONE,
        "confirmed_in_run_id" integer,
        "confirmed_at" TIMESTAMP WITH TIME ZONE,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_candidates_article_company" UNIQUE ("article_id", "company_id"),
        CONSTRAINT "CHK_candidates_only_mentions_confirmed" CHECK ("relevance" = 'relevant' OR ("sentiment" IS NULL AND "confirmed_in_run_id" IS NULL AND "confirmed_at" IS NULL)),
        CONSTRAINT "CHK_candidates_method_iff_judged" CHECK (("relevance" = 'pending') = ("relevance_method" IS NULL)),
        CONSTRAINT "PK_candidates" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(
      `CREATE INDEX "IDX_candidates_confirmed_in_run" ON "candidates" ("confirmed_in_run_id")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_candidates_company_relevance" ON "candidates" ("company_id", "relevance")`,
    );

    // Alert Digests
    await queryRunner.query(`
      CREATE TABLE "alert_digests" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "run_id" integer NOT NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "acknowledged_at" TIMESTAMP WITH TIME ZONE,
        CONSTRAINT "UQ_alert_digests_run" UNIQUE ("run_id"),
        CONSTRAINT "PK_alert_digests" PRIMARY KEY ("id")
      )`);
    await queryRunner.query(
      `CREATE INDEX "IDX_alert_digests_unacknowledged" ON "alert_digests" ("created_at") WHERE "acknowledged_at" IS NULL`,
    );
    await queryRunner.query(`
      CREATE TABLE "alert_digest_items" (
        "digest_id" integer NOT NULL,
        "candidate_id" integer NOT NULL,
        CONSTRAINT "PK_alert_digest_items" PRIMARY KEY ("digest_id", "candidate_id")
      )`);
    await queryRunner.query(
      `CREATE INDEX "IDX_alert_digest_items_candidate" ON "alert_digest_items" ("candidate_id")`,
    );

    // Foreign keys
    await queryRunner.query(
      `ALTER TABLE "run_company_errors" ADD CONSTRAINT "FK_run_company_errors_run" FOREIGN KEY ("run_id") REFERENCES "runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "run_company_errors" ADD CONSTRAINT "FK_run_company_errors_company" FOREIGN KEY ("company_id") REFERENCES "tracked_companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "candidates" ADD CONSTRAINT "FK_candidates_article" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "candidates" ADD CONSTRAINT "FK_candidates_company" FOREIGN KEY ("company_id") REFERENCES "tracked_companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "candidates" ADD CONSTRAINT "FK_candidates_fetched_in_run" FOREIGN KEY ("fetched_in_run_id") REFERENCES "runs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "candidates" ADD CONSTRAINT "FK_candidates_confirmed_in_run" FOREIGN KEY ("confirmed_in_run_id") REFERENCES "runs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "alert_digests" ADD CONSTRAINT "FK_alert_digests_run" FOREIGN KEY ("run_id") REFERENCES "runs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "alert_digest_items" ADD CONSTRAINT "FK_alert_digest_items_digest" FOREIGN KEY ("digest_id") REFERENCES "alert_digests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "alert_digest_items" ADD CONSTRAINT "FK_alert_digest_items_candidate" FOREIGN KEY ("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    // Dropping a table drops its indexes and the foreign keys it holds.
    for (const table of [
      'alert_digest_items',
      'alert_digests',
      'candidates',
      'articles',
      'run_company_errors',
      'tracked_companies',
      'collector_heartbeat',
      'runs',
    ]) {
      await queryRunner.query(`DROP TABLE "${table}"`);
    }
    for (const type of [
      'sentiment',
      'relevance_method',
      'candidate_relevance',
      'tracked_company_status',
      'collector_state',
      'run_trigger',
      'run_status',
      'run_type',
    ]) {
      await queryRunner.query(`DROP TYPE "${type}"`);
    }
  }
}
